# Generated by Django 6.0.4 on 2026-04-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('timeout', models.PositiveIntegerField(help_text='Timeout duration in seconds')),
                ('alert_email', models.EmailField(help_text='Email address for alert notifications', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('down', 'Down')], db_index=True, default='active', help_text='Current status of the monitor', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Timestamp of the last heartbeat received', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the monitor will expire if no heartbeat', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='monitors_mo_status_158466_idx')],
            },
        ),
    ]
